[[mounts]]
source = "/data"
destination = "/app/data"
type = "volume"

[build]
builder = "dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
DATA_DIR = "/app/data"
PYTHONUNBUFFERED = "1"
